
# tap repositories and their packages

tap homebrew/core
tap homebrew/cask
tap rcmdnk/file

brew brew-file

brew ack
brew direnv
brew ffmpeg
brew ghq
brew graphviz
brew go
brew hub
brew imagemagick
brew jq
brew kube-ps1
brew kubectx
brew shyiko/kubesec/kubesec
brew kubernetes-cli
brew kubernetes-helm
brew kustomize
brew libsodium
brew lv
brew mas
brew mitmproxy
brew mono
brew mpv
brew mysql@5.7
brew nmap
brew openssh
brew openssl
brew p7zip
brew peco
brew pwgen
brew rbenv
brew readline
brew redis
brew ruby-build
brew rtmpdump
brew shellcheck
brew stern
brew terraform
brew terraformer
brew w3m
brew wget
brew x265
brew yarn
brew youtube-dl
brew zsh
brew zsh-completions

tap rcmdnk/homebrew-rcmdnkpac
brew screenutf8

cask adobe-acrobat-reader
cask appcleaner
cask caffeine
cask controlplane
cask docker
cask dotnet-sdk
cask dropbox
cask firefox
cask geektool
cask google-chrome
cask google-cloud-sdk
cask google-japanese-ime
cask hyperswitch
cask iterm2
cask java
cask jupyter-notebook-ql
cask kindle
cask onyx
cask quicklook-csv
cask simplefloatingclock
cask skitch
cask unity-hub
cask visual-studio-code
cask virtualbox
cask vlc
cask wireshark
cask xld

tap delphinus/macvim-kaoriya
cask macvim-kaoriya-override
