
# tap repositories and their packages

tap homebrew/core
tap homebrew/cask
tap rcmdnk/file

brew brew-file

brew ack
brew ffmpeg
brew ghq
brew go
brew imagemagick
brew jq
brew kube-ps1
brew kubectx
brew kubernetes-cli
brew kubernetes-helm
brew kustomize
brew lv
brew macvim-kaoriya
brew mas
brew mitmproxy
brew mpv
brew openssh
brew openssl
brew peco
brew pwgen
brew readline
brew rbenv
brew ruby-build
brew rtmpdump
brew stern
brew w3m
brew wget
brew x265
brew yarn
brew youtube-dl
brew zsh
brew zsh-completions

tap rcmdnk/homebrew-rcmdnkpac
brew screenutf8

cask adobe-acrobat-reader
cask appcleaner
cask caffeine
cask controlplane
cask docker
cask dropbox
cask firefox
cask geektool
cask google-chrome
cask google-cloud-sdk
cask google-japanese-ime
cask hyperswitch
cask iterm2
cask jupyter-notebook-ql
cask kindle
cask macvim
cask onyx
cask qlimagesize
cask qlprettypatch
cask quicklook-csv
cask simplefloatingclock
cask virtualbox
cask vlc
cask xld
cask wireshark

# App Store applications
appstore 406056744 Evernote (7.5.2)
appstore 408981434 iMovie (10.1.9)
appstore 409183694 Keynote (8.2)
appstore 409201541 Pages (7.2)
appstore 409203825 Numbers (5.2)
appstore 497799835 Xcode (10.0)
appstore 539883307 LINE (5.10.1)
appstore 682658836 GarageBand (10.2.0)
appstore 803453959 Slack (3.3.2)
